In [1]:
import numpy as np
import pandas as pd

In [2]:
AND = pd.DataFrame({'x1':(0,0,0,0,1,1,1,1),'x2':(0,0,1,1,0,0,1,1),'x3':(0,1,0,1,0,1,0,1),'y':(0,0,0,0,0,0,0,1)})
AND

x1  x2  x3  y
0   0   0   0  0
1   0   0   1  0
2   0   1   0  0
3   0   1   1  0
4   1   0   0  0
5   1   0   1  0
6   1   1   0  0
7   1   1   1  1

In [3]:
weights = np.random.randn(4)*1e-4
weights

array([-1.27627727e-04, -4.11346212e-06, -1.26823008e-04, -4.27775419e-06])

In [4]:
inputs = AND[['x1','x2','x3']]
output = AND['y']
output

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    1
Name: y, dtype: int64

In [5]:
g = lambda inputs,weights:np.where(np.dot(inputs,weights)>0,1,0)

In [6]:
-np.ones((len(inputs),1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.]])

In [7]:
def train(inputs,output,weights,learning_factor,iterations):
    inputs1 = np.c_[inputs,-np.ones((len(inputs),1))]
    for n in range(iterations):
        activation = g(inputs1,weights)
        print(n,activation)
        weights -= learning_factor*np.dot(np.transpose(inputs1), (activation - output))
        print(n,weights)
    return weights

In [8]:
w = train(inputs,output,weights,0.01,20)
w

0 [1 0 1 0 0 0 0 0]
0 [ 9.87237227e-03 -4.11346212e-06  9.87317699e-03  9.99572225e-03]
1 [0 0 0 0 0 1 0 1]
1 [-1.27627727e-04 -4.11346212e-06 -1.26823008e-04  1.99957222e-02]
2 [0 0 0 0 0 0 0 0]
2 [0.00987237 0.00999589 0.00987318 0.00999572]
3 [0 0 1 1 0 1 1 1]
3 [-0.01012763 -0.02000411 -0.01012682  0.04999572]
4 [0 0 0 0 0 0 0 0]
4 [-0.00012763 -0.01000411 -0.00012682  0.03999572]
5 [0 0 0 0 0 0 0 0]
5 [ 9.87237227e-03 -4.11346212e-06  9.87317699e-03  2.99957222e-02]
6 [0 0 0 0 0 0 0 0]
6 [0.01987237 0.00999589 0.01987318 0.01999572]
7 [0 0 0 1 0 1 1 1]
7 [-0.00012763 -0.01000411 -0.00012682  0.04999572]
8 [0 0 0 0 0 0 0 0]
8 [ 9.87237227e-03 -4.11346212e-06  9.87317699e-03  3.99957222e-02]
9 [0 0 0 0 0 0 0 0]
9 [0.01987237 0.00999589 0.01987318 0.02999572]
10 [0 0 0 0 0 1 0 1]
10 [0.00987237 0.00999589 0.00987318 0.03999572]
11 [0 0 0 0 0 0 0 0]
11 [0.01987237 0.01999589 0.01987318 0.02999572]
12 [0 0 0 1 0 1 1 1]
12 [-1.27627727e-04 -4.11346212e-06 -1.26823008e-04  5.99957222e-02

array([0.01987237, 0.01999589, 0.01987318, 0.03999572])