In [5]:
#Question 1

import numpy as np
N = 4
def Vandermonde(a):
    x = np.ones(len(a))
    for i in range(N):
        if i !=0:
            x = np.column_stack((a**(i),x))
    print(x)
y = np.array([2,3,4])   
Vandermonde(y)

[[ 8.  4.  2.  1.]
 [27.  9.  3.  1.]
 [64. 16.  4.  1.]]


In [6]:
#Question 1 alternate answer

N = 4
x = np.array([2,3,4]) 
def  Vandermonde(x):
    print(np.column_stack([x**(N-1-i) for i in range(N)]))
Vandermonde(x)

[[ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [7]:
#Question 2

import numpy as np

lst = []  # creating an empty list 

n = int(input("Enter number of elements : ")) # number of elemetns as input 

for i in range(0, n): 
    ele = int(input()) 
    lst.append(ele) # adding the element 
    
lst = np.array(lst) # converting list to array

print("Sequence array = ",lst) 

k = int(input("Enter window size ")) #window size

z = []

for i in range(n-k+1):
    sum = 0
    
    for j in range(k):
        sum = sum + lst[i+j]
        
    avg = sum/k
    
    z.append(avg)
    
m = np.array(z)

print("OUTPUT IS: ",m.T)

Enter number of elements : 13
3
5
7
2
8
10
11
65
72
81
99
100
150
Sequence array =  [  3   5   7   2   8  10  11  65  72  81  99 100 150]
Enter window size 3
OUTPUT IS:  [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
